CREATE USER creds PASSWORD '1234';

CREATE SCHEMA IF NOT EXISTS creds;

GRANT ALL ON SCHEMA creds TO creds;
GRANT ALL ON ALL SEQUENCES IN SCHEMA creds TO creds;

ALTER DEFAULT PRIVILEGES
    FOR USER postgres
    IN SCHEMA creds
    GRANT ALL ON TABLES TO creds;
ALTER DEFAULT PRIVILEGES
    FOR USER postgres
    IN SCHEMA creds
    GRANT ALL ON SEQUENCES TO creds;

ALTER USER creds SET search_path TO creds, public;